export const SCOPES_OF_APPLICATIONS = [
  "aminozuursynthese",
  "bindweefsel",
  "bloed",
  "bloeddruk",
  "bloedglucose",
  "bloedstolling",
  "bloedvaten",
  "botten (kinderclaim)",
  "botten - collageen/bot",
  "botten - collageen/kraakbeen",
  "botten - instandhouding",
  "botten - menopauze (ziekterisicobeperkende claim)",
  "botten - opname calcium en fosfor",
  "celdeling",
  "celmembranen",
  "cholesterol - instandhouden",
  "cholesterol - verlagen (ziekterisicobeperkende claim)",
  "cognitief",
  "cognitief (kinderclaim)",
  "cysteïnesynthese",
  "dna-synthese",
  "eiwitsynthese",
  "electrolytenbalans",
  "energie",
  "fysieke prestatie",
  "fysische en cognitieve functies",
  "gewicht",
  "gewicht - vervanging 1 hoofdmaaltijd",
  "gewicht - vervanging 2 hoofdmaaltijden",
  "gezichtsvermogen - foetus/zuigelingen (kinderclaim)",
  "gezichtsvermogen - instandhouding",
  "gezichtsvermogen - zuigelingen (kinderclaim)",
  "groei (kinderclaim)",
  "haar",
  "hart",
  "hersenen - foetus/zuigelingen (kinderclaim)",
  "hersenen - instandhouding",
  "homocysteïne",
  "hormonen",
  "huid",
  "ijzer",
  "immuunsysteem (kinderclaim)",
  "immuunsysteem - fysieke inspanning",
  "immuunsysteem - normale werking",
  "jetlag",
  "lever",
  "lichaamstemperatuur",
  "macronutrienten",
  "metabolisme - eiwitten/glycogeen",
  "metabolisme - hormonen/vitd/neurotransmitters",
  "metabolisme - koolhydraat",
  "metabolisme - lipiden",
  "metabolisme - vetzuren",
  "metabolisme - vitamine a",
  "metabolisme - zuurbase",
  "metabolisme - zwavelaminozuur",
  "mond en gebit - instandhouding tanden",
  "mond en gebit - mineralisatie",
  "mond en gebit - mineralisatie/tandbederf (ziekterisicobeperkende claim)",
  "mond en gebit - monddroogte",
  "mond en gebit - plaquezuren",
  "mond en gebit - plaquezuren/tandbederf (ziekterisicobeperkende claim)",
  "mond en gebit - tandplak/kinderen (ziekterisicobeperkende claim)",
  "mond en gebit - tandvlees",
  "nagels",
  "oxidatieve schade",
  "psychologische functie",
  "regeneratie vitamine e",
  "schildklier",
  "slaap",
  "slijmvliezen",
  "spermatogenese",
  "spieren - groei",
  "spieren - herstel",
  "spieren - instandhouden",
  "spieren - valrisico (ziekterisicobeperkende claim)",
  "spieren - werking",
  "spijsvertering fecale bulk",
  "spijsvertering lactose",
  "spijsvertering overig",
  "spijsvertering transit",
  "triglyceriden",
  "vermoeidheid",
  "wateropname",
  "zenuwstelsel",
  "zuurstoftransport",
  "zwangerschap",
  "zwangerschap (ziekterisicobeperkende claim)",
];

export const NUTRIENTS = [
  "actieve kool",
  "alfa-cyclodextrine",
  "alfa-linoleenzuur (ala)",
  "alfa-linoleenzuur (ala) en linolzuur (la)",
  "arabinoxylaan geproduceerd uit tarwe-endosperm",
  "betaïne",
  "biotine (vitamine b8)",
  "bèta-glucaan van haver",
  "bètaglucaan uit gerst",
  "bètaglucanen",
  "bètaglucanen uit haver en gerst",
  "calcium",
  "calcium en vitamine d",
  "chitosan",
  "chloride",
  "choline",
  "chroom",
  "creatine",
  "docosahexaeenzuur (dha)",
  "docosahexaeenzuur (dha) en eicosapentaeenzuur (epa)",
  "eicosapentaeenzuur en docosahexaeen-zuur (epa/dha)",
  "eiwitten",
  "enkelvoudig en/of meervoudig onverzadigde vetzuren",
  "flavonolen uit cacao",
  "fluoride",
  "folaat (vitamine b11)",
  "foliumzuur",
  "fosfor",
  "fructose",
  "gedroogde pruimen van „pruimedanten”- cultivars (prunus domestica l.)",
  "gerstgraanvezels",
  "glucomannan (konjac mannan)",
  "guargom",
  "havergraanvezels",
  "hydroxypropyl-methylcellulose (hpmc)",
  "ijzer",
  "jodium",
  "kalium",
  "kauwgom zonder suiker",
  "kauwgom zonder suiker met carbamide",
  "koolhydraat-electrolytoplossingen",
  "koolhydraten",
  "koolhydraten, niet-vergistbare",
  "koolhydraten, niet-verteerbare",
  "koper",
  "lactase-enzym",
  "lactitol",
  "lactulose",
  "langzaam verteerbaar zetmeel",
  "levende yoghurtculturen",
  "levensmiddelen met een laag of verlaagd gehalte aan natrium",
  "levensmiddelen met een laag of verlaagd gehalte aan verzadigde vetzuren",
  "linolzuur",
  "maaltijdvervangend product voor gewichtsbeheersing",
  "magnesium",
  "mangaan",
  "melatonine",
  "met 100 % xylitol gezoete kauwgum",
  "molybdeen",
  "monascus purpureus (rood gefermenteerde rijst)",
  "niacine (vitamine b3)",
  "oliezuur",
  "pantotheenzuur (vitamine b5)",
  "pectinen",
  "plantenstanolesters",
  "plantensterolen en plantenstanolen",
  "plantensterolen/plantenstanolesters",
  "plantensterolen: uit planten geëxtraheerde sterolen, vrij of veresterd met vetzuren van levensmiddelenkwaliteit",
  "polyfenolen in olijfolie",
  "resistent zetmeel",
  "riboflavine (vitamine b2)",
  "roggevezels",
  "seleen",
  "suikerbietvezels",
  "suikervervangers, d.w.z. intense zoetstoffen; xylitol, sorbitol, mannitol, maltitol, lactitol, isomalt, erythritol, sucralose en polydextrose; d-tagatose en isomaltulose",
  "tarwezemelenvezels",
  "thiamine (vitamine b1)",
  "vitamine a",
  "vitamine b12",
  "vitamine b6",
  "vitamine c",
  "vitamine d",
  "vitamine e",
  "vitamine k",
  "vlees of vis",
  "walnoten",
  "water",
  "zink",
  "zure alcoholvrije dranken met een nieuwe formulering met: - minder dan 1 g fermenteerbare koolhydraten per 100 ml (suikers en andere koolhydraten, met uitzondering van polyolen); - 0,3 tot 0,8 mol calcium per mol voedingszuur; - ph-waarde tussen 3,7 en 4,0.",
];
